Complement of french translation
wintercms/wn-user-plugin pull request #15
Opened 2022-03-10 10:43 UTC by GrCOTE7

For backend message about connexion mode

2022-03-10 11:36 UTC, mjauvin requested changes
It's better to use double quotes when single quotes are needed within the string.

2022-03-10 11:36 UTC, mjauvin commented on lang/fr/lang.php
> +        'remember_login_comment' => 'Selectionner si la session de l\'utilisateur doit être persistente.',
```suggestion
        'remember_login_comment' => "Selectionner si la session de l'utilisateur doit être persistente." ,
```

2022-03-10 11:36 UTC, mjauvin commented on lang/fr/lang.php
> +        'remember_ask' => 'Demander  à l\'utilisateur lors de la connexion',
```suggestion
        'remember_ask' => "Demander  à l'utilisateur lors de la connexion",
```

2022-03-22 20:18 UTC, LukeTowers commented on lang/fr/lang.php
> +        'remember_ask' => 'Demander à l\'utilisateur lors de la connexion',
```suggestion
        'remember_ask' => "Demander à l'utilisateur lors de la connexion",
```

2025-02-26 07:14 UTC, merged